# Generated by Django 4.2.2 on 2023-06-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('value1', 'Par chèque'), ('value2', 'Par éspèces'), ('value3', 'Par virement')], default='value2', max_length=10),
        ),
    ]
