# Generated by Django 4.2.2 on 2023-06-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
        ('orders', '0003_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderProduct', to='home.product'),
        ),
    ]
